name: SHAKE256
type: xof
checksumsmall: 5c88f8cc3210246c1fb9fdf84b686b024d80f35a061b4208d35a77b3aed9acab
checksumbig: 013aa03ebe252ca0e7b00733443583546e8580dedadab428db3801381743dbd7
implementations:
    - name: amd64/spec
      version: TODO
      supported_platforms:
        - architecture: x86_64
          operating_systems:
              - Linux
              - Darwin
          required_flags: # FIXME
              - popcnt
    - name: amd64/ref
      version: TODO
      supported_platforms:
        - architecture: x86_64
          operating_systems:
              - Linux
              - Darwin
          required_flags: # FIXME
              - popcnt
    - name: amd64/avx2
      version: TODO
      supported_platforms:
        - architecture: x86_64
          operating_systems:
              - Linux
              - Darwin
          required_flags: #FIXME
              - avx2
