name: SHA-256
type: hash
checksumsmall: ebbed3a47232047ad399cb77b6324d6c902f4715de871750545b1a3b12046ebe
checksumbig: 86f524b63449ca0d5c29e58e7bc22c279187af259f83d6eecfb51db5c8d511e9
implementations:
    - name: amd64/ref
      version: TODO
      supported_platforms:
        - architecture: x86_64
          operating_systems:
              - Linux
              - Darwin
          required_flags: # FIXME
              - popcnt
    - name: amd64/avx2
      version: TODO
      supported_platforms:
        - architecture: x86_64
          operating_systems:
              - Linux
              - Darwin
          required_flags: #FIXME
              - avx2
