name: SHA-512
type: hash
checksumsmall: 8220572f58bd4730be165c9739d8d4b0fd2e0229dbe01e25b4aed23f00f23b70
checksumbig: c1e322b7cbfc941260c5508967ba05bce22eeee94d425e708b7c3301ea1d5e2e
implementations:
    - name: amd64/ref
      version: TODO
      supported_platforms:
        - architecture: x86_64
          operating_systems:
              - Linux
              - Darwin
          required_flags: # FIXME
              - popcnt
