# --------------------------------------------------------------------
AS      ?= as
CC      ?= gcc
CFLAGS  ?= -O3 -Wall -Wextra -Wpedantic -Wvla -Werror -std=c99 \
	         -Wundef -Wshadow -Wcast-align -Wpointer-arith -Wmissing-prototypes\
	         -fstrict-aliasing -fno-common -pipe -g

# --------------------------------------------------------------------
