ECFN := -f namespace -f namespace_xor -f namespace_ic -f namespace_xor_ic
SRCS := stream.jazz
include ../../../../../crypto_stream/chacha/common/amd64/avx/Flags.mk
include ../../../../../Makefile.common
