#!/usr/bin/env bash

label=$1
top=$(cd "$(dirname "$0")/../../../" ; pwd -P)
dir=$top/$2
wcard=$3

RED="\e[31m"
YELLOW='\e[33m'
GREEN="\e[32m"
BOLD="\e[1m"
NORMAL="\e[0m"

warning=$(mktemp)
error=$(mktemp)

situation_status()
{
  pattern=$1;
  output=$2;

  find $dir -name $pattern | \
  while read file; do
   d=$(dirname $file);
   nd=${d/$dir\//}; #nd=${nd/\/.ci/};
   b=$(basename $file);
   c=$(cat $file | wc -l);
   echo "$c, $nd/$b";
  done | \
  sort -t',' -g -k1 | sed -e 's/^[ \t]*//' -e 's/, \.\//, /' > $output
}

situation_status "${wcard}.log" $warning;
situation_status "${wcard}.error" $error;

# situation status
echo -e "${BOLD}$label: ${NORMAL}"

# print good situations in 'green'
cat $warning | egrep -E "^0, " | \
while read line; do
 echo -e "${GREEN}${BOLD}OK, ${line}${NORMAL}"
done

# print non-severe situations in 'yellow'
cat $warning | egrep -vE "^0, " | \
while read line; do
 echo -e "${YELLOW}${BOLD}W, ${line}${NORMAL}"
done

# print complicated situations in 'red'
cat $error | \
while read line; do
 echo -e "${RED}${BOLD}E, ${line}${NORMAL}"
done

rm $warning $error

