#!/bin/bash

#
# how to use jcmp1:
# $ scripts/ci/jcmp baseline.csv input.csv output.csv 
#

baseline="$1"
input="$2"
output="$3"

paste -d' ' \
  <(cat $baseline | cut -d',' -f1 | sed -e 's/^ //') \
  <(cat $baseline | cut -d',' -f2 | sed -e 's/^ //') \
  <(cat $input    | cut -d',' -f2 | sed -e 's/^ //') \
| awk '{printf "%ld, %ld, %ld, %.02f\n", $1, $2, $3, (($3*100/$2)-100)}' > $output

cat $output | \
awk 'BEGIN { FS = ", "; sum = 0; } ; { sum+=$4; } ; END { print sum / NR }' > ${output/.csv/.avg}
