#!/bin/bash

#
# how to use jcmp0:
# $ scripts/ci/jcmp baseline.csv input.csv output.csv 
#

baseline="$1"
input="$2"
output="$3"

paste -d' ' \
  <(cat $baseline) \
  <(cat $input) \
| awk '{printf "%ld,%ld,%.03f\n", $1, $2, (($2*100.0/$1)-100.0)}' > $output

cat $output | \
awk 'BEGIN { FS = ","; sum = 0; } ; { sum+=$3; } ; END { print sum / NR }' > ${output/.csv/.avg}
