#!/bin/bash

# how to use jcmp:
# $ scripts/ci/jcmp baseline.csv input.csv output.csv 
#

top=$(cd "$(dirname "$0")/../" ; pwd -P)
baseline="$1"
input="$2"
output="$3"

paste -d' ' \
  <(cat $baseline | cut -d',' -f1 | sed -e 's/^ //') \
  <(cat $baseline | cut -d',' -f2 | sed -e 's/^ //') \
  <(cat $input    | cut -d',' -f2 | sed -e 's/^ //') \
  \
| awk '{printf "%s, %.02f\n", $1, (($3*100/$2)-100)}' > $output

