#!/bin/bash

RED='\033[0;31m'
YELLOW='\033[1;33m'
GREEN='\033[0;32m'
BOLD='\033[1m'
NORMAL='\033[0m'

warning=$(mktemp)
error=$(mktemp)

implementations_status()
{
  pattern=$1;
  output=$2;

  find . -name $pattern | \
  while read file; do
   d=$(dirname $(dirname $file));
   c=$(cat $file | wc -l);
   echo "$c, $d";
  done | \
  sort -t',' -g -k1 | sed -e 's/, \.\//, /' > $output
}

implementations_status '*_s.log' $warning;
implementations_status '*_s.error' $error;

# compilation status
echo -e "${BOLD}Compilation status: ${NORMAL}" 

# print implementations with zero warnings in 'green'
cat $warning | egrep -E "^0, " | \
while read line; do
 echo -e "${GREEN}${BOLD}${line}${NORMAL}" 
done

# print implementations with some warnings in 'yellow'
cat $warning | egrep -vE "^0, " | \
while read line; do
 echo -e "${YELLOW}${BOLD}${line}${NORMAL}" 
done

# print non-compiling implementations in red 'yellow'
cat $error | \
while read line; do
 echo -e "${RED}${BOLD}${line}${NORMAL}" 
done

rm $warning $error

