#!/usr/bin/env bash

git clone https://gitlab.com/jasmin-lang/jasmin-compiler.git
cd jasmin-compiler/compiler
git fetch -a
git checkout main
nix-channel --update
nix-shell --command "NIX_CFLAGS_COMPILE=\"$NIX_CFLAGS_COMPILE --sysroot=/\"; make"
./jasminc -help
