#!/usr/bin/env bash

git clone https://github.com/jasmin-lang/jasmin.git
cd jasmin/
git fetch -a
git checkout main
nix-channel --update
nix-shell --command "cd compiler && make CIL"
cd compiler/
nix-shell --command "NIX_CFLAGS_COMPILE=\"$NIX_CFLAGS_COMPILE --sysroot=/\" && make"
./jasminc -help
