#!/usr/bin/env bash

git clone https://github.com/jasmin-lang/jasmin.git
cd jasmin/
git fetch -a
git checkout main
nix-channel --update
nix-shell --command "cd compiler && make CIL && make"
./compiler/jasminc -help
