name: Poly1305
type: onetimeauth
checksumsmall: 6e0b9cab26afe89025afa79802234668b378ae2a0f8415b062ece0174f8bdcef
checksumbig: d31323d65ade3ad4f87a77aef4c31e87c3aecf32087f2706cf43f81b3b0868b9
implementations:
    - name: amd64/ref
      version: 0.1
      supported_platforms:
        - architecture: x86_64
          operating_systems:
              - Linux
              - Darwin
    - name: amd64/mmx
      version: 0.1
      supported_platforms:
        - architecture: x86_64
          operating_systems:
              - Linux
              - Darwin
    - name: amd64/avx
      version: 0.1
      supported_platforms:
        - architecture: x86_64
          operating_systems:
              - Linux
              - Darwin
          required_flags:
              - avx
    - name: amd64/avx2
      version: 0.1
      supported_platforms:
        - architecture: x86_64
          operating_systems:
              - Linux
              - Darwin
          required_flags:
              - avx2

