name: X-Wing
type: kem
checksumsmall:
checksumbig:
claimed-nist-level: 3
claimed-security: IND-CCA2
length-public-key: 1216
length-ciphertext: 1120
length-secret-key: 2464
length-shared-secret: 32
principal-submitters:
  - TODO
auxiliary-submitters:
  - TODO
implementations:
    - name: amd64/ref
      version: TODO
      supported_platforms:
        - architecture: x86_64
          operating_systems:
              - Linux
              - Darwin
          required_flags: # FIXME
              - avx2
              - bmi2
              - popcnt