name: X-Wing
type: kem
checksumsmall: 844bca7a113f642135f10d7ab047f8fbc137a6d0c7bbe64dbde0b48c46681872
checksumbig: 05451934bd516a3b885896e7e448d9739ed1ccc67339f438db230bd479f026bb
claimed-nist-level: 3
claimed-security: IND-CCA2
length-public-key: 1216
length-ciphertext: 1120
length-secret-key: 2464
length-shared-secret: 32
principal-submitters:
  - TODO
auxiliary-submitters:
  - TODO
implementations:
    - name: amd64/ref
      version: TODO
      supported_platforms:
        - architecture: x86_64
          operating_systems:
              - Linux
              - Darwin
          required_flags: # FIXME
              - avx2
              - bmi2
              - popcnt