ECFN := -ec namespace -ec namespace_xor -ec namespace_ic -ec namespace_xor_ic
SRCS := stream.jazz
include ../../../../../crypto_stream/chacha/common/amd64/avx/Flags.mk
include ../../../../../Makefile.common
