name: Chacha20
type: stream
checksumsmall: 022fe9b47a01f938ab0f62e248c51fd42c732a7a218017b504a1dcec912d9d82
checksumbig: 8a63a16e033fca40b110ac7ac2ff16f39eae00956055408bdbd72b9ace68a220
implementations:
    - name: amd64/ref
      version: TODO
      supported_platforms:
        - architecture: x86_64
          operating_systems:
              - Linux
              - Darwin
          required_flags: # FIXME
              - popcnt
    - name: amd64/ref2
      version: TODO
      supported_platforms:
        - architecture: x86_64
          operating_systems:
              - Linux
              - Darwin
          required_flags: # FIXME
              - popcnt
    - name: amd64/mmx
      version: TODO
      supported_platforms:
        - architecture: x86_64
          operating_systems:
              - Linux
              - Darwin
          required_flags: # FIXME
              - popcnt
    - name: amd64/avx
      version: TODO
      supported_platforms:
        - architecture: x86_64
          operating_systems:
              - Linux
              - Darwin
          required_flags: # FIXME
              - avx
    - name: amd64/avx2
      version: TODO
      supported_platforms:
        - architecture: x86_64
          operating_systems: # FIXME
              - Linux
              - Darwin
          required_flags:
              - avx2
