#ifndef JADE_STREAM_API_H
#define JADE_STREAM_API_H

#include "namespace.h"

#define JADE_STREAM_KEYBYTES NAMESPACE(KEYBYTES)
#define JADE_STREAM_NONCEBYTES NAMESPACE(NONCEBYTES)

#define jade_stream_xor NAMESPACE_LC(xor)
#define jade_stream JADE_NAMESPACE_LC

#define JADE_STREAM_ALGNAME NAMESPACE(ALGNAME)
#define JADE_STREAM_ARCH NAMESPACE(ARCH)
#define JADE_STREAM_IMPL NAMESPACE(IMPL)

#endif
