#ifndef JADE_SIGN_API_H
#define JADE_SIGN_API_H

#include "namespace.h"

#define JADE_SIGN_PUBLICKEYBYTES NAMESPACE(PUBLICKEYBYTES)
#define JADE_SIGN_SECRETKEYBYTES NAMESPACE(SECRETKEYBYTES)
#define JADE_SIGN_BYTES NAMESPACE(BYTES)
#define JADE_SIGN_DETERMINISTIC NAMESPACE(DETERMINISTIC)

#define jade_sign_keypair NAMESPACE_LC(keypair)
#define jade_sign JADE_NAMESPACE_LC
#define jade_sign_open NAMESPACE_LC(open)

#define JADE_SIGN_ALGNAME NAMESPACE(ALGNAME)
#define JADE_SIGN_ARCH NAMESPACE(ARCH)
#define JADE_SIGN_IMPL NAMESPACE(IMPL)

#endif
