#ifndef JADE_SECRETBOX_API_H
#define JADE_SECRETBOX_API_H

#include "namespace.h"

#define JADE_SECRETBOX_KEYBYTES NAMESPACE(KEYBYTES)
#define JADE_SECRETBOX_NONCEBYTES NAMESPACE(NONCEBYTES)
#define JADE_SECRETBOX_ZEROBYTES NAMESPACE(ZEROBYTES)
#define JADE_SECRETBOX_BOXZEROBYTES NAMESPACE(BOXZEROBYTES)

#define jade_secretbox_open NAMESPACE_LC(open)
#define jade_secretbox JADE_NAMESPACE_LC

#define JADE_SECRETBOX_ALGNAME NAMESPACE(ALGNAME)
#define JADE_SECRETBOX_ARCH NAMESPACE(ARCH)
#define JADE_SECRETBOX_IMPL NAMESPACE(IMPL)

#endif
