#ifndef JADE_SCALARMULT_API_H
#define JADE_SCALARMULT_API_H

#include "namespace.h"

#define JADE_SCALARMULT_BYTES NAMESPACE(BYTES)
#define JADE_SCALARMULT_SCALARBYTES NAMESPACE(SCALARBYTES)

#define jade_scalarmult JADE_NAMESPACE_LC
#define jade_scalarmult_base NAMESPACE_LC(base)

#define JADE_SCALARMULT_ALGNAME NAMESPACE(ALGNAME)
#define JADE_SCALARMULT_ARCH NAMESPACE(ARCH)
#define JADE_SCALARMULT_IMPL NAMESPACE(IMPL)

#endif
