#ifndef JADE_ONETIMEAUTH_API_H
#define JADE_ONETIMEAUTH_API_H

#include "namespace.h"

#define JADE_ONETIMEAUTH_BYTES NAMESPACE(BYTES)
#define JADE_ONETIMEAUTH_KEYBYTES NAMESPACE(KEYBYTES)

#define jade_onetimeauth_verify NAMESPACE_LC(verify)
#define jade_onetimeauth JADE_NAMESPACE_LC

#define JADE_ONETIMEAUTH_ALGNAME NAMESPACE(ALGNAME)
#define JADE_ONETIMEAUTH_ARCH NAMESPACE(ARCH)
#define JADE_ONETIMEAUTH_IMPL NAMESPACE(IMPL)

#endif
